# Generated by Django 2.2.19 on 2023-10-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_new_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
    ]
