# Generated by Django 2.2.19 on 2023-10-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20231019_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Tournament',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='tournament',
        ),
    ]
