# Generated by Django 2.2.19 on 2023-10-19 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20231019_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
