# Generated by Django 2.2.19 on 2023-10-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20231019_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.Tournament'),
            preserve_default=False,
        ),
    ]
